languageCode = "en-us"
defaultContentLanguage = "en"
metaDataFormat = "yaml"
baseurl = "https://soypunk.me/"
title = "soypunk"
canonifyurls = false
PluralizeListTitles = false
googleAnalytics = "UA-37885618-1"
enableRobotsTXT = true
paginate = 15
staticDir = ["static", "media"]
#sectionPagesMenu = "main"


[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"

[permalinks]
	pages = "/:slug"
	posts = "/:year/:month/:day/:slug"
	archives = "/:slug/"

[author]
	name = "Shawn Medero"
	handle = "soypunk"
	aboutPage = "/about"
	location = "Claremont, CA"    

[indexes]
    tag = "tags"

[taxonomies]
	tag = "tags"
	2011 = "2011"
	2013 = "2013"
	2014 = "2014"
	2017 = "2017"
	2018 = "2018"
	archive = "archives"	

[params]
	blogSubtitle = ""
	description = ""
	owner = "Shawn Medero"
	twitter = "https://twitter.com/soypunk"
	mainSections = "stories, recaps, players, links"
	env	= "PRODUCTION"
#	env	= "DEV"
	
[[menu.main]]
	name = "About"
	weight = 1
	identifier = "about"
	url = "/about/"

#[[menu.main]]
#	name = "Archives"
#	weight = 2
#	identifier = "archives"
#	url = "/posts/"

# [[menu.main]]
#	name = "Photos"
#	weight = 3
#	identifier = "photos"
#	url = "/photos/"