languageCode = "en-us"
title = "Shawn Medero"
baseurl = "https://soypunk.me/"
canonifyurls = false
PluralizeListTitles = false
googleAnalytics = ""
enableRobotsTXT = true
DefaultContentLanguage = "en"
metaDataFormat = "yaml"
paginate = 15

[sitemap]
	changefreq = "monthly"
	priority = 0.5
	filename = "sitemap.xml"

[permalinks]
	posts = "/posts/:year/:month/:day/:slug"
	links = "/links/:year/:month/:day/:slug"
	minis = "/tweets/:year/:month/:day/:slug"

[author]
    name = "Shawn Medero"

[indexes]
    tag = "tags"
    topic = "topics"

[taxonomies]
	category = "topics"
	tag = "tags"

[params]
	blogSubtitle = ""
	description = ""
	owner = "Shawn Medero"
	twitter = "https://twitter.com/soypunk"
	mainSections = "stories, recaps, players, links"
	env	= "PRODUCTION"	